default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: uberzeit_development

test:
  <<: *default
  database: uberzeit_test

production:
  <<: *default
  database: <%= ENV.fetch('UBERZEIT_DATABASE', 'uberzeit_production') %>
