development:
  ubertrack_hosts:
    redmine: 'http://redmine.dev'
    otrs: 'http://10.10.10.17'

staging:
  ubertrack_hosts:
    redmine: 'https://redmine-staging.nine.ch'
    otrs: 'https://otrs-staging.nine.ch'

production:
  ubertrack_hosts:
    redmine: 'https://redmine.nine.ch'
    otrs: 'https://otrs.nine.ch'
